### ISSUE TITLE
No Openai key found....

### ISSUE THREAD

**Issue by kkohlmannY** [ericciarla/babyagijs#1]
Hi, I am getting the following error when trying to run npm start.

/babyagijs/node_modules/langchain/dist/llms/openai.js:131
            throw new Error("OpenAI API key not found");
                  ^

Error: OpenAI API key not found
    at OpenAI (C:\Users\kkohl\Documents\GitHub\babyagijs\node_modules\langchain\src\llms\openai.ts:149:13)
    at <anonymous> (c:\Users\kkohl\Documents\GitHub\babyagijs\src\index.ts:15:13)
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.9.0

does this support gpt-3.5 or only gpt-4 ?

**Comment by ericciarla** [comment]
What does your .env look like?

**Comment by kallebornemark** [comment]
@ericciarla There was nothing about `.env` in the instructions.

**Comment by ericciarla** [comment]
I will add more on the .env soon

**Comment by ericciarla** [comment]
@kkohlmannY @kallebornemark I added a .env.example to the repo :)
